/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tags: Tag;
    media: Media;
    posts: Post;
    'work-experience': WorkExperience;
    testimonials: Testimonial;
    services: Service;
    'quote-requests': QuoteRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'work-experience': WorkExperienceSelect<false> | WorkExperienceSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'testimonials-page': TestimonialsPage;
    'quote-page': QuotePage;
    'archive-settings': ArchiveSetting;
    'project-template': ProjectTemplate;
    'system-pages': SystemPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'testimonials-page': TestimonialsPageSelect<false> | TestimonialsPageSelect<true>;
    'quote-page': QuotePageSelect<false> | QuotePageSelect<true>;
    'archive-settings': ArchiveSettingsSelect<false> | ArchiveSettingsSelect<true>;
    'project-template': ProjectTemplateSelect<false> | ProjectTemplateSelect<true>;
    'system-pages': SystemPagesSelect<false> | SystemPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin';
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  /**
   * Generated from the name when left empty.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  uploadedBy?: (string | null) | User;
  usageType: 'cover' | 'inline' | 'og' | 'generic';
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  kind: 'article' | 'project';
  status: 'draft' | 'published';
  /**
   * Set automatically on first publish.
   */
  publishedAt?: string | null;
  /**
   * Generated from the title when left empty. Locked after publishing.
   */
  slug: string;
  author: string | User;
  tags?: (string | Tag)[] | null;
  title: string;
  /**
   * Shown on cards and lists, and used as the SEO description unless one is set.
   */
  excerpt: string;
  /**
   * External articles appear in article lists but open on the original platform and do not create a local detail page.
   */
  publicationType?: ('native' | 'external') | null;
  /**
   * The original article URL.
   */
  externalUrl?: string | null;
  /**
   * Sets the "Read on …" link. Detected from the URL when left empty.
   */
  externalPlatform?: ('medium' | 'linkedin' | 'other') | null;
  externalCtaLabel?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Projects fall back to the first gallery image.
   */
  coverImage?: (string | null) | Media;
  /**
   * Your role, shown on project previews and the case study.
   */
  projectRole?: string | null;
  /**
   * One-line result for homepage project cards, e.g. "Test coverage raised from 10% to 80%".
   */
  projectOutcome?: string | null;
  /**
   * Ordered project gallery.
   */
  projectGallery?: (string | Media)[] | null;
  /**
   * Defaults to the title.
   */
  seoTitle?: string | null;
  /**
   * Defaults to the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Social share image. Defaults to the cover image.
   */
  ogImage?: (string | null) | Media;
  /**
   * Only when this content first appeared on another site.
   */
  canonicalUrl?: string | null;
  noindex?: boolean | null;
  readingTimeMinutes?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-experience".
 */
export interface WorkExperience {
  id: string;
  company: string;
  role: string;
  period: string;
  location?: string | null;
  website?: string | null;
  summary: string;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sortOrder: number;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  role: string;
  company?: string | null;
  relationship: 'manager' | 'colleague' | 'client' | 'other';
  /**
   * Use the source wording exactly. Short excerpts work best on the site.
   */
  quote: string;
  recommendationDate?: string | null;
  sourceLabel?: string | null;
  sourceUrl?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Engagement types shown on the homepage. Add one row per way to work together.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Short name, e.g. "Consultancy" or "Technical co-founder".
   */
  title: string;
  /**
   * One or two sentences on the card: who it is for and what they get.
   */
  summary: string;
  /**
   * Optional short points, e.g. "Architecture review", "Hiring plan". Up to four.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Contact wizard intent this card preselects. Must match a Contact page "Help types" value, e.g. "Project or services" or "Consultancy".
   */
  contactIntent: string;
  /**
   * Link text on the card, e.g. "Start a project enquiry".
   */
  ctaLabel: string;
  showOnHome?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: string;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  helpType: string;
  workType?: string | null;
  timeline?: string | null;
  budget?: string | null;
  context: string;
  wantsReply?: boolean | null;
  preferredContact?: string | null;
  status: 'new' | 'contacted' | 'closed' | 'spam';
  sourceUrl?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'work-experience';
        value: string | WorkExperience;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: string | QuoteRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  uploadedBy?: T;
  usageType?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  kind?: T;
  status?: T;
  publishedAt?: T;
  slug?: T;
  author?: T;
  tags?: T;
  title?: T;
  excerpt?: T;
  publicationType?: T;
  externalUrl?: T;
  externalPlatform?: T;
  externalCtaLabel?: T;
  content?: T;
  coverImage?: T;
  projectRole?: T;
  projectOutcome?: T;
  projectGallery?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  noindex?: T;
  readingTimeMinutes?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-experience_select".
 */
export interface WorkExperienceSelect<T extends boolean = true> {
  company?: T;
  role?: T;
  period?: T;
  location?: T;
  website?: T;
  summary?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sortOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  relationship?: T;
  quote?: T;
  recommendationDate?: T;
  sourceLabel?: T;
  sourceUrl?: T;
  featured?: T;
  sortOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  contactIntent?: T;
  ctaLabel?: T;
  showOnHome?: T;
  sortOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  helpType?: T;
  workType?: T;
  timeline?: T;
  budget?: T;
  context?: T;
  wantsReply?: T;
  preferredContact?: T;
  status?: T;
  sourceUrl?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  name: string;
  shortLabel: string;
  professionalTitle: string;
  defaultSeoTitle: string;
  defaultSeoDescription: string;
  logo?: (string | null) | Media;
  /**
   * Fallback public path used when no logo media item is selected.
   */
  logoPath?: string | null;
  logoAlt: string;
  portrait?: (string | null) | Media;
  /**
   * Fallback path, such as /images/usman.jpg.
   */
  portraitPath?: string | null;
  portraitAlt: string;
  resumeLink?: string | null;
  email: string;
  phone?: string | null;
  meetingLink: string;
  socialLinks?:
    | {
        name: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  navigation?:
    | {
        label: string;
        url: string;
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerDescription: string;
  bookCall: {
    title: string;
    description: string;
    buttonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  seoTitle: string;
  seoDescription: string;
  eyebrow: string;
  headline: string;
  supportingText: string;
  trustChips?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel: string;
  secondaryCtaLabel: string;
  /**
   * Optional reassurance line under the hero buttons, e.g. what the call covers.
   */
  primaryCtaNote?: string | null;
  postHeroLine: string;
  /**
   * Short label above the company list, e.g. "Trusted by teams at".
   */
  proofTitle?: string | null;
  /**
   * Company or client names shown under the homepage introduction.
   */
  proofCompanies?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Up to four headline numbers backed by case studies or experience.
   */
  proofStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  writingsTitle: string;
  /**
   * One line under the homepage Articles heading.
   */
  writingsDescription?: string | null;
  writingsArchiveLabel: string;
  writingsLimit?: number | null;
  projectsTitle: string;
  projectsArchiveLabel: string;
  featuredProjects?: (string | Post)[] | null;
  /**
   * Heading of the homepage "Ways to work together" section. Leave empty to hide the section.
   */
  servicesTitle?: string | null;
  /**
   * One sentence under the services heading.
   */
  servicesDescription?: string | null;
  servicesLimit?: number | null;
  testimonialsEyebrow: string;
  testimonialsTitle: string;
  testimonialsDescription: string;
  testimonialsArchiveLabel?: string | null;
  testimonialLimit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  seoTitle: string;
  seoDescription: string;
  eyebrow: string;
  title: string;
  summary?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  video?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    url?: string | null;
    transcript?: string | null;
    transcriptLabel?: string | null;
  };
  experienceTitle: string;
  strengths?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  strengthsTitle: string;
  /**
   * Optional quote shown on the About page. Leave empty to hide the section.
   */
  featuredTestimonial?: (string | null) | Testimonial;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-page".
 */
export interface TestimonialsPage {
  id: string;
  seoTitle: string;
  seoDescription: string;
  eyebrow: string;
  title: string;
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-page".
 */
export interface QuotePage {
  id: string;
  seoTitle: string;
  seoDescription: string;
  eyebrow: string;
  title: string;
  description: string;
  process?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  responseNote: string;
  privacyNote: string;
  nextStepsTitle: string;
  alternativesTitle: string;
  callLabel: string;
  emailLinkLabel: string;
  formEyebrow: string;
  formTitle: string;
  requiredFieldsLabel: string;
  scopeLegend: string;
  selectPlaceholder: string;
  helpTypeLabel: string;
  workTypeLabel: string;
  timelineLabel: string;
  budgetLabel: string;
  helpTypes: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  workTypes: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  timelines: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  budgets: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  contactMethods: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  contextLabel: string;
  contextPlaceholder: string;
  contextLegend: string;
  contextHelp: string;
  contactLegend: string;
  nameLabel: string;
  namePlaceholder: string;
  emailLabel: string;
  emailPlaceholder: string;
  companyLabel: string;
  companyPlaceholder: string;
  preferredContactLabel: string;
  submitLabel: string;
  submittingLabel: string;
  successMessage: string;
  errorMessage: string;
  successEyebrow: string;
  successTitle: string;
  sendAnotherLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archive-settings".
 */
export interface ArchiveSetting {
  id: string;
  writingsTitle: string;
  writingsDescription: string;
  writingsSeoDescription: string;
  filterTitle: string;
  filterDescription: string;
  postsPerPage?: number | null;
  writingCtaLabel: string;
  readArticleLabel: string;
  projectsTitle: string;
  projectsDescription: string;
  projectsSeoDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-template".
 */
export interface ProjectTemplate {
  id: string;
  backLabel: string;
  stackLabel: string;
  linkLabel: string;
  defaultLinkLabel: string;
  linkDescription: string;
  storyTitle: string;
  previousLabel: string;
  nextLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-pages".
 */
export interface SystemPage {
  id: string;
  notFoundTitle: string;
  notFoundMessage: string;
  thankYouTitle: string;
  thankYouMessage: string;
  homeButtonLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  shortLabel?: T;
  professionalTitle?: T;
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  logo?: T;
  logoPath?: T;
  logoAlt?: T;
  portrait?: T;
  portraitPath?: T;
  portraitAlt?: T;
  resumeLink?: T;
  email?: T;
  phone?: T;
  meetingLink?: T;
  socialLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        isPrimary?: T;
        id?: T;
      };
  footerDescription?: T;
  bookCall?:
    | T
    | {
        title?: T;
        description?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  eyebrow?: T;
  headline?: T;
  supportingText?: T;
  trustChips?:
    | T
    | {
        text?: T;
        id?: T;
      };
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  primaryCtaNote?: T;
  postHeroLine?: T;
  proofTitle?: T;
  proofCompanies?:
    | T
    | {
        text?: T;
        id?: T;
      };
  proofStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  writingsTitle?: T;
  writingsDescription?: T;
  writingsArchiveLabel?: T;
  writingsLimit?: T;
  projectsTitle?: T;
  projectsArchiveLabel?: T;
  featuredProjects?: T;
  servicesTitle?: T;
  servicesDescription?: T;
  servicesLimit?: T;
  testimonialsEyebrow?: T;
  testimonialsTitle?: T;
  testimonialsDescription?: T;
  testimonialsArchiveLabel?: T;
  testimonialLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  eyebrow?: T;
  title?: T;
  summary?:
    | T
    | {
        text?: T;
        id?: T;
      };
  video?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        url?: T;
        transcript?: T;
        transcriptLabel?: T;
      };
  experienceTitle?: T;
  strengths?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  strengthsTitle?: T;
  featuredTestimonial?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-page_select".
 */
export interface TestimonialsPageSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-page_select".
 */
export interface QuotePageSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  responseNote?: T;
  privacyNote?: T;
  nextStepsTitle?: T;
  alternativesTitle?: T;
  callLabel?: T;
  emailLinkLabel?: T;
  formEyebrow?: T;
  formTitle?: T;
  requiredFieldsLabel?: T;
  scopeLegend?: T;
  selectPlaceholder?: T;
  helpTypeLabel?: T;
  workTypeLabel?: T;
  timelineLabel?: T;
  budgetLabel?: T;
  helpTypes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  workTypes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  timelines?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  budgets?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contactMethods?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contextLabel?: T;
  contextPlaceholder?: T;
  contextLegend?: T;
  contextHelp?: T;
  contactLegend?: T;
  nameLabel?: T;
  namePlaceholder?: T;
  emailLabel?: T;
  emailPlaceholder?: T;
  companyLabel?: T;
  companyPlaceholder?: T;
  preferredContactLabel?: T;
  submitLabel?: T;
  submittingLabel?: T;
  successMessage?: T;
  errorMessage?: T;
  successEyebrow?: T;
  successTitle?: T;
  sendAnotherLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archive-settings_select".
 */
export interface ArchiveSettingsSelect<T extends boolean = true> {
  writingsTitle?: T;
  writingsDescription?: T;
  writingsSeoDescription?: T;
  filterTitle?: T;
  filterDescription?: T;
  postsPerPage?: T;
  writingCtaLabel?: T;
  readArticleLabel?: T;
  projectsTitle?: T;
  projectsDescription?: T;
  projectsSeoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-template_select".
 */
export interface ProjectTemplateSelect<T extends boolean = true> {
  backLabel?: T;
  stackLabel?: T;
  linkLabel?: T;
  defaultLinkLabel?: T;
  linkDescription?: T;
  storyTitle?: T;
  previousLabel?: T;
  nextLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-pages_select".
 */
export interface SystemPagesSelect<T extends boolean = true> {
  notFoundTitle?: T;
  notFoundMessage?: T;
  thankYouTitle?: T;
  thankYouMessage?: T;
  homeButtonLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}